name: "Context"

on:
  push:
    branches:
      - main

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
    env: 
        MY_ACTION: ${{ github.action}}
      - name: "step 1"
        run: |
          echo "Hello! $MY_ACTION"