name: "Dep jobs example"

on: ['push']

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: stepB
        run: echo "World"
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: stepA
        run: echo "Hello"